import { Inter, Karantina, Jost, Josefin_Sans, Limelight } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const karantina = Karantina({
  subsets: ["latin"],
  weight: ['300', '400', '700'],
  variable: '--font-karantina'
});
const limelight = Limelight({ subsets: ["latin"], weight:['400'], variable:'--font-limelight'});
const jost = Jost({ subsets: ["latin"], variable: '--font-jost' });
const josefinSans = Josefin_Sans({ subsets: ["latin"], variable: '--font-josefinSans' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" className={`${inter.variable} ${karantina.variable} ${jost.variable} ${josefinSans.variable} ${limelight.variable}`}>
      <body className={`${inter.className} ${karantina.className} ${jost.className} ${josefinSans.className} ${limelight.variable}`}>
      {children}
      </body>
      </html>
  );
}
